Drental/fvtt-tokenactionhud

- scripts/actions/pf2e/pf2e-actions.js
- scripts/rollHandlers/pf2e/pf2e-base.js
- scripts/tokenactionhud.js
> restore hovering, signature spells and multi roll

- scripts/actions/d35e/d35e-actions.js
> Fix for 3.5e skills

- scripts/actions/od6s/od6s-actions.js
Made some changes to the system.json for certain action types which require an update.  Also noticed that specializations were not included in the skill list, so added those.
> OpenD6 Space: Update actions, add specializations to skills list

- scripts/tokenactionhud.js
> fix an error caused by assuming an actor exists

- scripts/actions/sfrpg/sfrpg-actions.js
as well as all similar problems (data -> data.data) and deprecations I could find in sfrpg-actions.js
Fixes #34
> Fixes missing spells tab for SFRPG 

- scripts/actions/wfrp4e/wfrp4e-actions.js
- scripts/rollHandlers/wfrp4e/wfrp-base.js
fixes for WFRP 4.0.0 version and foundry 0.8
> wfrp4 update

- scripts/actions/kamigakari/kg-actions.js
- scripts/rollHandlers/kamigakari/kg-base.js
Updates based on some system changes
> Kamigakari System Update

- scripts/actions/lancer/lancer-actions.js
- scripts/rollHandlers/lancer/lancer-base.js
Update to the Lancer module, in anticipation of the upcoming 1.0 release for the Lancer system.
> Update to the Lancer module.

- scripts/actions/symbaroum/symbaroum-actions.js
- scripts/rollHandlers/symbaroum/symbaroum-base.js
- added symbaroum traits
- Abilities, Powers and traits without a script won't appear anymore
- clean-up code
- -added icons in hud
> Symbaroum update

- lang/en.json
- lang/fr.json
> Fix missing comma

- scripts/actions/lancer/lancer-actions.js
> Lancer Module: Await mm promise

- lang/br.json
- lang/cn.json
- lang/de.json
- lang/en.json
- lang/es.json
- lang/fr.json
- lang/ja.json
- lang/ko.json
- lang/pl.json
- scripts/actions/actionHandler.js
- scripts/actions/pf1/pf1-actions.js
- scripts/rollHandlers/pf1/pf1-base.js
I've done a few things here.
The first is that I've renamed the spellbooks so that they follow what the player sees in their spellbook tabs in their character sheet. Once a spellbook is configured, by default it renames the spellbook to that class. That can be further overridden with a custom name. So basically it's altName > class > default -- where default is the legacy Primary/Secondary/etc that used to be the only option (it changed probably around February, but this mod is older than that so it only showed those legacy values--on the character data these are basically computed, so you've got to manually check altName then class before falling back to the default.
I also added a button for caster level check. This is pretty straightforward and basically follows the exact same logic as …
> Pf1 split spellbooks

- scripts/actions/od6s/od6s-actions.js
- scripts/rollHandlers/od6s/od6s-base.js
Adds vehicle actions to opend6-space-0.1.0
> Od6s 0.1.0 vehicle actions

- lang/fr.json
Add missing keys and their translation
> Add new french translations

- scripts/actions/od6s/od6s-actions.js
Moves OpenD6 Space vehicle actions to a separate category and adds resistance/shield rolls.
> OpenD6 Space Vehicle category

- module.json
- scripts/actions/ed4e/ed4e-actions.js
- scripts/init.js
- scripts/managers/ed4e.js
- scripts/managers/systemManagerFactory.js
- scripts/rollHandlers/ed4e/ed4e-base.js
- scripts/settings/ed4e-settings.js
As discussed with Drental in Discord, I created the necessary code to include the _Earthdawn_ system.
> Add new system "Earthdawn 4e"

- lang/en.json
- readme.md
- scripts/actions/dnd4e/dnd4e-actions.js
- scripts/rollHandlers/dnd4e/dnd4e-base.js
- scripts/settings/dnd4e-settings.js
Hud now includes items
Fixed sort issue that wouldn't show certain powers
Moved any 4E method calls to an API so 4E system doesn't break them later down the line
Added 4E to readme.md
> Update to D&D 4E integration

- scripts/actions/pf2e/pf2e-actions.js
> Fix pf2e spell modifiers

- scripts/rollHandlers/pf2e/pf2e-base.js
Allows chat portrait modules to natively use token art for sender
> Adds scene to speaker to resolve token

- scripts/actions/cthack/cthack-actions.js
- scripts/rollHandlers/cthack/cthack-base.js
Moreover, in the Required Game Systems in the Foundry page, could you add the missing systems which are already implemented please :
Chroniques Oubliées Fantasy : https://foundryvtt.com/packages/cof
Cthulhu Hack : https://foundryvtt.com/packages/cthack
Morover in the Foundry research page :
There a 2 missing systems also : cof and cthack
Thanks for your work !
> Cthulhu Hack new features

- lang/en.json
- module.json
- scripts/actions/gurps/gurps-actions.js
- scripts/init.js
- scripts/managers/gurps.js
- scripts/managers/systemManagerFactory.js
- scripts/rollHandlers/gurps/gurps-base.js
- scripts/settings/gurps-settings.js
Thank you again for all of your help.   I knew that once I got started, it would be very easy.    Your model works so beautifully, and our game system has a very powerful chat command system, so I only needed a single roll handler that just executed what we call an "On-the-Fly" formula (OTF).   
I reset the modules.json to the minified version and tested, and it worked fine.
You can see it in action in this zipped up WEBM file:
[TokenActionHudGURPS.zip](https://github.com/Drental/fvtt-tokenactionhud/files/8177017/TokenActionHudGURPS.zip)
> Adding GURPS

- module.json
- scripts/actions/gurps/gurps-actions.js
- scripts/settings/gurps-settings.js
Fixed issue if a single weapon provided both Melee and Ranged attacks.
I added actions for Reaction and Conditional modifiers.
I protected the module setting for list size, in case the user does not enter a number.
> Version 3 of GURPS support

- scripts/actions/dnd4e/dnd4e-actions.js
- scripts/rollHandlers/dnd4e/dnd4e-base.js
As above, the corresponding change in D&D 4E system was merged a while ago so this is all ready to go.
> DND 4E: Added Action Point, 2nd Wind and Deathsave

- module.json
- scripts/actions/space1889/space1889-actions.js
- scripts/init.js
- scripts/managers/space1889.js
- scripts/managers/systemManagerFactory.js
- scripts/rollHandlers/space1889/space1889-base.js
- scripts/settings/space1889-settings.js
adding Support for:
Unofficial SPACE 1889 Ubiquity system for FoundryVTT
https://github.com/Scepfari/SPACE1889-FVTT
>  Support for SPACE 1889 System #194

- lang/ja.json
I am using it with WFRP4e, but it was not translated into Japanese, so I added a translation based on the latest language file.
> update ja.lang: reflect the latest langae files. translated for wfrp4e.

- module.json
- scripts/actions/coc7/coc7-actions.js
- scripts/init.js
- scripts/managers/coc7.js
- scripts/managers/systemManagerFactory.js
- scripts/rollHandlers/coc7/coc7-base.js
- scripts/settings/coc7-settings.js
Adding support for
Call of Cthulhu 7th Edition (Unofficial)
https://foundryvtt.com/packages/CoC7
> Add support for Call of Cthulhu 7th Edition (Unofficial)

- scripts/rollHandlers/lancer/lancer-base.js
This is a quick fix for the lancer system that makes tech attacks work properly on the latest version.  I'll do a proper update soon schedule permitting.
> Lancer: Quick fix for tech attacks.

- lang/en.json
- lang/fr.json
- Add news keys in French file
- Add missing key for co sytems in English file
> Update french and english keys

- scripts/rollHandlers/dnd4e/dnd4e-base.js
Allows fast-forwarding initative with no popups
> 4E: passed event into initative roll

- scripts/actions/alienrpg/alienrpg-actions.js
- scripts/actions/categories/macroHelper.js
- scripts/actions/co/co-actions.js
- scripts/actions/cthack/cthack-actions.js
- scripts/actions/dnd5e/dnd5e-actions.js
- scripts/actions/exampleActionHandler.js
- scripts/actions/forbiddenlands/forbiddenlands-actions.js
- scripts/actions/kamigakari/kg-actions.js
- scripts/actions/wfrp4e/wfrp4e-actions.js
- scripts/rollHandlers/dnd5e/dnd5e-base.js
A lot of fixes, so Token Action HUD won't throw errors left and right. :)
> V10 compat

- lang/en.json
- module.json
- scripts/init.js
- scripts/managers/manager.js
- scripts/settings.js
- scripts/tokenactionhud.js
- styles/token-action-hud.css
- Color Picker: Add Color Picker library for module settings.
- Color Buttons: Add settings to color button background and border.
> Color Picker, Color Buttons

- scripts/actions/space1889/space1889-actions.js
SPACE 1889: Entry "Active Defense" is missing for creatures #274
> Bugfix: #274

- .github/workflows/main.yml
- changelog.md
- module.json
- scripts/init.js
- scripts/settings.js
- scripts/tokenactionhud.js
- styles/token-action-hud.css
- adds support for libThemer ColorPicker and ColorSettings.
- Moves ColorPicker and ColorSettings to `relationships.flags.optional` / `relationships.optional`
- Adds changelog.md to package
> All The Color Options

- lang/en.json
- scripts/init.js
as someone who desperately tries to have as few modules as possible active...
> reduce nagging

- lang/en.json
- module.json
- scripts/actions/cyphersystem/cyphersystem-actions.js
- scripts/init.js
- scripts/managers/cyphersystem.js
- scripts/managers/systemManagerFactory.js
- scripts/rollHandlers/cyphersystem/cyphersystem-base.js
- scripts/settings/cyphersystem-settings.js
This pull request adds support for the cyphersystem game system, version 2.1.0 and later
> Add support for 'cyphersystem'

- scripts/actions/cyphersystem/cyphersystem-actions.js
- scripts/rollHandlers/cyphersystem/cyphersystem-base.js
Update the Skills and Abilities in the Cypher System so that they are grouped by the Categories defined on the Actor.
> Cypher System: Sort Abilities and Skills into Categories

- scripts/actions/gurps/gurps-actions.js
Add hearing, vision, taste/smell, touch attributes.
Add OTFs for equipment
Add HP/FP buttons
Fix accuracy buttons (if accuracy was "+0")
> Update for GURPS

- scripts/actions/pf2e/pf2e-actions.js
Fixes #355. I recently noticed this in my own game so I thought I'd contribute a fix.
> Hide unidentified pf2e effects for non-GM users

- lang/fr.json
I'm suggesting you should consider to use the weblate foundry-hub to easy the translation update.
> Update of french keys

- scripts/actions/swade/swade-actions.js
> SWADE improvements 2
